package postgres_outbound_adapter

import (
	"prabogo/internal/model"
	outbound_port "prabogo/internal/port/outbound"

	"github.com/doug-martin/goqu/v9"
)

const tableUser = "users"
const tableRole = "roles"

type authAdapter struct {
	db outbound_port.DatabaseExecutor
}

func NewAuthAdapter(
	db outbound_port.DatabaseExecutor,
) outbound_port.AuthDatabasePort {
	return &authAdapter{
		db: db,
	}
}

func (adapter *authAdapter) SaveUser(user model.User) error {
	dataset := goqu.Dialect("postgres").
		Insert(tableUser).
		Rows(user)

	query, _, err := dataset.ToSQL()
	if err != nil {
		return err
	}

	// Handle Upsert if needed, or just insert
	// For now simple insert, but maybe on conflict update?
	// The user model has ID. If it's new, ID is generated by DB default or passed?
	// Migration says DEFAULT uuid_generate_v4().
	// Model has ID field.
	// If ID is zero uuid, we let DB handle it? But user struct has ID.
	// Let's assume Insert

	_, err = adapter.db.Exec(query)
	return err
}

func (adapter *authAdapter) FindUserByFilter(filter model.UserFilter, lock bool) (result []model.User, err error) {
	dialect := goqu.Dialect("postgres")
	dataset := dialect.From(tableUser)
	dataset = addAuthFilter(dataset, filter)

	query, _, err := dataset.ToSQL()
	if err != nil {
		return nil, err
	}

	if lock {
		query += " FOR UPDATE"
	}

	res, err := adapter.db.Query(query)
	if err != nil {
		return nil, err
	}
	defer res.Close()

	users := []model.User{}
	for res.Next() {
		var u model.User
		// Scanning all fields.
		// Need to be careful with scanners.
		// using standard Scan
		err := res.Scan(
			&u.ID,
			&u.Username,
			&u.Email,
			&u.EncryptedPassword,
			&u.Fullname,
			&u.Phone,
			&u.Avatar,
			&u.RoleID,
			&u.UserRole,
			&u.Status,
			&u.LastLogin,
			&u.LastIP,
			&u.FailedLoginAttempts,
			&u.LockedUntil,
			&u.PasswordChangedAt,
			&u.ForcePasswordChange,
			&u.TwoFactorEnabled,
			&u.TwoFactorSecret,
			&u.APIToken,
			&u.APITokenExpiresAt,
			&u.CreatedBy,
			&u.UpdatedBy,
			&u.CreatedAt,
			&u.UpdatedAt,
		)
		if err != nil {
			return nil, err
		}
		users = append(users, u)
	}

	return users, nil
}

func (adapter *authAdapter) FindRoleByName(name string) (*model.Role, error) {
	dialect := goqu.Dialect("postgres")
	dataset := dialect.From(tableRole).Where(goqu.Ex{"name": name})

	query, _, err := dataset.ToSQL()
	if err != nil {
		return nil, err
	}

	row := adapter.db.QueryRow(query)
	var r model.Role
	err = row.Scan(
		&r.ID,
		&r.Name,
		&r.DisplayName,
		&r.Description,
		&r.Permissions,
		&r.IsSystem,
		&r.IsActive,
		&r.CreatedAt,
		&r.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &r, nil

}

func addAuthFilter(dataset *goqu.SelectDataset, filter model.UserFilter) *goqu.SelectDataset {
	if len(filter.IDs) > 0 {
		dataset = dataset.Where(goqu.Ex{"id": filter.IDs})
	}

	if len(filter.Emails) > 0 {
		dataset = dataset.Where(goqu.Ex{"email": filter.Emails})
	}

	if len(filter.Usernames) > 0 {
		dataset = dataset.Where(goqu.Ex{"username": filter.Usernames})
	}

	return dataset
}
