// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "MikrOps/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockUserDatabasePort is a mock of UserDatabasePort interface.
type MockUserDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockUserDatabasePortMockRecorder
}

// MockUserDatabasePortMockRecorder is the mock recorder for MockUserDatabasePort.
type MockUserDatabasePortMockRecorder struct {
	mock *MockUserDatabasePort
}

// NewMockUserDatabasePort creates a new mock instance.
func NewMockUserDatabasePort(ctrl *gomock.Controller) *MockUserDatabasePort {
	mock := &MockUserDatabasePort{ctrl: ctrl}
	mock.recorder = &MockUserDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDatabasePort) EXPECT() *MockUserDatabasePortMockRecorder {
	return m.recorder
}

// AssignUserRole mocks base method.
func (m *MockUserDatabasePort) AssignUserRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignUserRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignUserRole indicates an expected call of AssignUserRole.
func (mr *MockUserDatabasePortMockRecorder) AssignUserRole(ctx, userID, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignUserRole", reflect.TypeOf((*MockUserDatabasePort)(nil).AssignUserRole), ctx, userID, roleID)
}

// CreateUser mocks base method.
func (m *MockUserDatabasePort) CreateUser(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserDatabasePortMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserDatabasePort)(nil).CreateUser), ctx, user)
}

// DeleteUser mocks base method.
func (m *MockUserDatabasePort) DeleteUser(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserDatabasePortMockRecorder) DeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserDatabasePort)(nil).DeleteUser), ctx, id)
}

// GetUserByID mocks base method.
func (m *MockUserDatabasePort) GetUserByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserDatabasePortMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserDatabasePort)(nil).GetUserByID), ctx, id)
}

// GetUsersByTenantID mocks base method.
func (m *MockUserDatabasePort) GetUsersByTenantID(ctx context.Context, tenantID uuid.UUID) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByTenantID", ctx, tenantID)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByTenantID indicates an expected call of GetUsersByTenantID.
func (mr *MockUserDatabasePortMockRecorder) GetUsersByTenantID(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByTenantID", reflect.TypeOf((*MockUserDatabasePort)(nil).GetUsersByTenantID), ctx, tenantID)
}

// ListUsers mocks base method.
func (m *MockUserDatabasePort) ListUsers(ctx context.Context, tenantID *uuid.UUID, limit, offset int) ([]model.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, tenantID, limit, offset)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserDatabasePortMockRecorder) ListUsers(ctx, tenantID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserDatabasePort)(nil).ListUsers), ctx, tenantID, limit, offset)
}

// UpdateUser mocks base method.
func (m *MockUserDatabasePort) UpdateUser(ctx context.Context, user *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserDatabasePortMockRecorder) UpdateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserDatabasePort)(nil).UpdateUser), ctx, user)
}
