// Code generated by MockGen. DO NOT EDIT.
// Source: profile.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "MikrOps/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockProfileDatabasePort is a mock of ProfileDatabasePort interface.
type MockProfileDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockProfileDatabasePortMockRecorder
}

// MockProfileDatabasePortMockRecorder is the mock recorder for MockProfileDatabasePort.
type MockProfileDatabasePortMockRecorder struct {
	mock *MockProfileDatabasePort
}

// NewMockProfileDatabasePort creates a new mock instance.
func NewMockProfileDatabasePort(ctrl *gomock.Controller) *MockProfileDatabasePort {
	mock := &MockProfileDatabasePort{ctrl: ctrl}
	mock.recorder = &MockProfileDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileDatabasePort) EXPECT() *MockProfileDatabasePortMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockProfileDatabasePort) CreateProfile(ctx context.Context, input model.CreateProfileRequest, mikrotikID uuid.UUID) (*model.MikrotikProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, input, mikrotikID)
	ret0, _ := ret[0].(*model.MikrotikProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockProfileDatabasePortMockRecorder) CreateProfile(ctx, input, mikrotikID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockProfileDatabasePort)(nil).CreateProfile), ctx, input, mikrotikID)
}

// CreateProfilePPPoE mocks base method.
func (m *MockProfileDatabasePort) CreateProfilePPPoE(ctx context.Context, profileID uuid.UUID, input model.CreateProfileRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfilePPPoE", ctx, profileID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProfilePPPoE indicates an expected call of CreateProfilePPPoE.
func (mr *MockProfileDatabasePortMockRecorder) CreateProfilePPPoE(ctx, profileID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfilePPPoE", reflect.TypeOf((*MockProfileDatabasePort)(nil).CreateProfilePPPoE), ctx, profileID, input)
}

// Delete mocks base method.
func (m *MockProfileDatabasePort) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProfileDatabasePortMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProfileDatabasePort)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockProfileDatabasePort) GetByID(ctx context.Context, id uuid.UUID) (*model.MikrotikProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.MikrotikProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProfileDatabasePortMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProfileDatabasePort)(nil).GetByID), ctx, id)
}

// GetByMikrotikID mocks base method.
func (m *MockProfileDatabasePort) GetByMikrotikID(ctx context.Context, mikrotikID, profileID uuid.UUID) (*model.MikrotikProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMikrotikID", ctx, mikrotikID, profileID)
	ret0, _ := ret[0].(*model.MikrotikProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMikrotikID indicates an expected call of GetByMikrotikID.
func (mr *MockProfileDatabasePortMockRecorder) GetByMikrotikID(ctx, mikrotikID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMikrotikID", reflect.TypeOf((*MockProfileDatabasePort)(nil).GetByMikrotikID), ctx, mikrotikID, profileID)
}

// List mocks base method.
func (m *MockProfileDatabasePort) List(ctx context.Context, mikrotikID uuid.UUID) ([]model.MikrotikProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, mikrotikID)
	ret0, _ := ret[0].([]model.MikrotikProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProfileDatabasePortMockRecorder) List(ctx, mikrotikID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProfileDatabasePort)(nil).List), ctx, mikrotikID)
}

// Update mocks base method.
func (m *MockProfileDatabasePort) Update(ctx context.Context, id uuid.UUID, input model.CreateProfileRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProfileDatabasePortMockRecorder) Update(ctx, id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProfileDatabasePort)(nil).Update), ctx, id, input)
}

// UpdateMikrotikObjectID mocks base method.
func (m *MockProfileDatabasePort) UpdateMikrotikObjectID(ctx context.Context, profileID uuid.UUID, objectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMikrotikObjectID", ctx, profileID, objectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMikrotikObjectID indicates an expected call of UpdateMikrotikObjectID.
func (mr *MockProfileDatabasePortMockRecorder) UpdateMikrotikObjectID(ctx, profileID, objectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMikrotikObjectID", reflect.TypeOf((*MockProfileDatabasePort)(nil).UpdateMikrotikObjectID), ctx, profileID, objectID)
}
