// Code generated by MockGen. DO NOT EDIT.
// Source: customer.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "MikrOps/internal/model"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockCustomerDatabasePort is a mock of CustomerDatabasePort interface.
type MockCustomerDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerDatabasePortMockRecorder
}

// MockCustomerDatabasePortMockRecorder is the mock recorder for MockCustomerDatabasePort.
type MockCustomerDatabasePortMockRecorder struct {
	mock *MockCustomerDatabasePort
}

// NewMockCustomerDatabasePort creates a new mock instance.
func NewMockCustomerDatabasePort(ctrl *gomock.Controller) *MockCustomerDatabasePort {
	mock := &MockCustomerDatabasePort{ctrl: ctrl}
	mock.recorder = &MockCustomerDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomerDatabasePort) EXPECT() *MockCustomerDatabasePortMockRecorder {
	return m.recorder
}

// CreateCustomer mocks base method.
func (m *MockCustomerDatabasePort) CreateCustomer(input model.CustomerInput, tenantID, mikrotikID uuid.UUID, mikrotikObjectID string) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomer", input, tenantID, mikrotikID, mikrotikObjectID)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomer indicates an expected call of CreateCustomer.
func (mr *MockCustomerDatabasePortMockRecorder) CreateCustomer(input, tenantID, mikrotikID, mikrotikObjectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomer", reflect.TypeOf((*MockCustomerDatabasePort)(nil).CreateCustomer), input, tenantID, mikrotikID, mikrotikObjectID)
}

// CreateCustomerService mocks base method.
func (m *MockCustomerDatabasePort) CreateCustomerService(tenantID, customerID, profileID uuid.UUID, price, taxRate float64, startDate time.Time) (*model.CustomerService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCustomerService", tenantID, customerID, profileID, price, taxRate, startDate)
	ret0, _ := ret[0].(*model.CustomerService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCustomerService indicates an expected call of CreateCustomerService.
func (mr *MockCustomerDatabasePortMockRecorder) CreateCustomerService(tenantID, customerID, profileID, price, taxRate, startDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCustomerService", reflect.TypeOf((*MockCustomerDatabasePort)(nil).CreateCustomerService), tenantID, customerID, profileID, price, taxRate, startDate)
}

// Delete mocks base method.
func (m *MockCustomerDatabasePort) Delete(tenantID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerDatabasePortMockRecorder) Delete(tenantID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Delete), tenantID, id)
}

// GetByID mocks base method.
func (m *MockCustomerDatabasePort) GetByID(tenantID, id uuid.UUID) (*model.CustomerWithService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", tenantID, id)
	ret0, _ := ret[0].(*model.CustomerWithService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCustomerDatabasePortMockRecorder) GetByID(tenantID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCustomerDatabasePort)(nil).GetByID), tenantID, id)
}

// GetByPPPoEUsername mocks base method.
func (m *MockCustomerDatabasePort) GetByPPPoEUsername(tenantID uuid.UUID, username string) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPPPoEUsername", tenantID, username)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPPPoEUsername indicates an expected call of GetByPPPoEUsername.
func (mr *MockCustomerDatabasePortMockRecorder) GetByPPPoEUsername(tenantID, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPPPoEUsername", reflect.TypeOf((*MockCustomerDatabasePort)(nil).GetByPPPoEUsername), tenantID, username)
}

// GetByUsername mocks base method.
func (m *MockCustomerDatabasePort) GetByUsername(tenantID, mikrotikID uuid.UUID, username string) (*model.Customer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", tenantID, mikrotikID, username)
	ret0, _ := ret[0].(*model.Customer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockCustomerDatabasePortMockRecorder) GetByUsername(tenantID, mikrotikID, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockCustomerDatabasePort)(nil).GetByUsername), tenantID, mikrotikID, username)
}

// List mocks base method.
func (m *MockCustomerDatabasePort) List(tenantID, mikrotikID uuid.UUID) ([]model.CustomerWithService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tenantID, mikrotikID)
	ret0, _ := ret[0].([]model.CustomerWithService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCustomerDatabasePortMockRecorder) List(tenantID, mikrotikID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCustomerDatabasePort)(nil).List), tenantID, mikrotikID)
}

// Update mocks base method.
func (m *MockCustomerDatabasePort) Update(tenantID, id uuid.UUID, input model.CustomerInput, price, taxRate float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tenantID, id, input, price, taxRate)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCustomerDatabasePortMockRecorder) Update(tenantID, id, input, price, taxRate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomerDatabasePort)(nil).Update), tenantID, id, input, price, taxRate)
}

// UpdateMikrotikObjectID mocks base method.
func (m *MockCustomerDatabasePort) UpdateMikrotikObjectID(tenantID, customerID uuid.UUID, objectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMikrotikObjectID", tenantID, customerID, objectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMikrotikObjectID indicates an expected call of UpdateMikrotikObjectID.
func (mr *MockCustomerDatabasePortMockRecorder) UpdateMikrotikObjectID(tenantID, customerID, objectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMikrotikObjectID", reflect.TypeOf((*MockCustomerDatabasePort)(nil).UpdateMikrotikObjectID), tenantID, customerID, objectID)
}

// UpdateStatus mocks base method.
func (m *MockCustomerDatabasePort) UpdateStatus(tenantID, id uuid.UUID, status model.CustomerStatus, ip, mac, interfaceName *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", tenantID, id, status, ip, mac, interfaceName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockCustomerDatabasePortMockRecorder) UpdateStatus(tenantID, id, status, ip, mac, interfaceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockCustomerDatabasePort)(nil).UpdateStatus), tenantID, id, status, ip, mac, interfaceName)
}

