// Code generated by MockGen. DO NOT EDIT.
// Source: cache_port.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "MikrOps/internal/model"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockPPPCachePort is a mock of PPPCachePort interface.
type MockPPPCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockPPPCachePortMockRecorder
}

// MockPPPCachePortMockRecorder is the mock recorder for MockPPPCachePort.
type MockPPPCachePortMockRecorder struct {
	mock *MockPPPCachePort
}

// NewMockPPPCachePort creates a new mock instance.
func NewMockPPPCachePort(ctrl *gomock.Controller) *MockPPPCachePort {
	mock := &MockPPPCachePort{ctrl: ctrl}
	mock.recorder = &MockPPPCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPPPCachePort) EXPECT() *MockPPPCachePortMockRecorder {
	return m.recorder
}

// GetCached mocks base method.
func (m *MockPPPCachePort) GetCached(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCached", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCached indicates an expected call of GetCached.
func (mr *MockPPPCachePortMockRecorder) GetCached(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCached", reflect.TypeOf((*MockPPPCachePort)(nil).GetCached), ctx, key)
}

// GetClient mocks base method.
func (m *MockPPPCachePort) GetClient(ctx context.Context, bearerKey string) (model.Client, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, bearerKey)
	ret0, _ := ret[0].(model.Client)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockPPPCachePortMockRecorder) GetClient(ctx, bearerKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockPPPCachePort)(nil).GetClient), ctx, bearerKey)
}

// GetPPPActive mocks base method.
func (m *MockPPPCachePort) GetPPPActive(ctx context.Context, tenantId string) ([]model.PPPActive, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPPPActive", ctx, tenantId)
	ret0, _ := ret[0].([]model.PPPActive)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPPPActive indicates an expected call of GetPPPActive.
func (mr *MockPPPCachePortMockRecorder) GetPPPActive(ctx, tenantId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPPPActive", reflect.TypeOf((*MockPPPCachePort)(nil).GetPPPActive), ctx, tenantId)
}

// GetPPPInactive mocks base method.
func (m *MockPPPCachePort) GetPPPInactive(ctx context.Context, tenantId string) ([]model.PPPActive, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPPPInactive", ctx, tenantId)
	ret0, _ := ret[0].([]model.PPPActive)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPPPInactive indicates an expected call of GetPPPInactive.
func (mr *MockPPPCachePortMockRecorder) GetPPPInactive(ctx, tenantId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPPPInactive", reflect.TypeOf((*MockPPPCachePort)(nil).GetPPPInactive), ctx, tenantId)
}

// GetTrafficData mocks base method.
func (m *MockPPPCachePort) GetTrafficData(ctx context.Context, key string) (*model.TrafficData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrafficData", ctx, key)
	ret0, _ := ret[0].(*model.TrafficData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrafficData indicates an expected call of GetTrafficData.
func (mr *MockPPPCachePortMockRecorder) GetTrafficData(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrafficData", reflect.TypeOf((*MockPPPCachePort)(nil).GetTrafficData), ctx, key)
}

// InvalidateCache mocks base method.
func (m *MockPPPCachePort) InvalidateCache(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateCache", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateCache indicates an expected call of InvalidateCache.
func (mr *MockPPPCachePortMockRecorder) InvalidateCache(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateCache", reflect.TypeOf((*MockPPPCachePort)(nil).InvalidateCache), ctx, key)
}

// SetCached mocks base method.
func (m *MockPPPCachePort) SetCached(ctx context.Context, key, value string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCached", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCached indicates an expected call of SetCached.
func (mr *MockPPPCachePortMockRecorder) SetCached(ctx, key, value, ttl interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCached", reflect.TypeOf((*MockPPPCachePort)(nil).SetCached), ctx, key, value, ttl)
}

// SetClient mocks base method.
func (m *MockPPPCachePort) SetClient(ctx context.Context, bearerKey string, client model.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetClient", ctx, bearerKey, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetClient indicates an expected call of SetClient.
func (mr *MockPPPCachePortMockRecorder) SetClient(ctx, bearerKey, client interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClient", reflect.TypeOf((*MockPPPCachePort)(nil).SetClient), ctx, bearerKey, client)
}

// SetPPPActive mocks base method.
func (m *MockPPPCachePort) SetPPPActive(ctx context.Context, tenantId string, data []model.PPPActive, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPPPActive", ctx, tenantId, data, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPPPActive indicates an expected call of SetPPPActive.
func (mr *MockPPPCachePortMockRecorder) SetPPPActive(ctx, tenantId, data, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPPPActive", reflect.TypeOf((*MockPPPCachePort)(nil).SetPPPActive), ctx, tenantId, data, hash)
}

// SetPPPInactive mocks base method.
func (m *MockPPPCachePort) SetPPPInactive(ctx context.Context, tenantId string, data []model.PPPActive, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPPPInactive", ctx, tenantId, data, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPPPInactive indicates an expected call of SetPPPInactive.
func (mr *MockPPPCachePortMockRecorder) SetPPPInactive(ctx, tenantId, data, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPPPInactive", reflect.TypeOf((*MockPPPCachePort)(nil).SetPPPInactive), ctx, tenantId, data, hash)
}

// SetTrafficData mocks base method.
func (m *MockPPPCachePort) SetTrafficData(ctx context.Context, key string, data *model.TrafficData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTrafficData", ctx, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTrafficData indicates an expected call of SetTrafficData.
func (mr *MockPPPCachePortMockRecorder) SetTrafficData(ctx, key, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrafficData", reflect.TypeOf((*MockPPPCachePort)(nil).SetTrafficData), ctx, key, data)
}
