// Code generated by MockGen. DO NOT EDIT.
// Source: registry_database.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	outbound_port "MikrOps/internal/port/outbound"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabasePort is a mock of DatabasePort interface.
type MockDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockDatabasePortMockRecorder
}

// MockDatabasePortMockRecorder is the mock recorder for MockDatabasePort.
type MockDatabasePortMockRecorder struct {
	mock *MockDatabasePort
}

// NewMockDatabasePort creates a new mock instance.
func NewMockDatabasePort(ctrl *gomock.Controller) *MockDatabasePort {
	mock := &MockDatabasePort{ctrl: ctrl}
	mock.recorder = &MockDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabasePort) EXPECT() *MockDatabasePortMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockDatabasePort) Auth() outbound_port.AuthDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth")
	ret0, _ := ret[0].(outbound_port.AuthDatabasePort)
	return ret0
}

// Auth indicates an expected call of Auth.
func (mr *MockDatabasePortMockRecorder) Auth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockDatabasePort)(nil).Auth))
}

// Client mocks base method.
func (m *MockDatabasePort) Client() outbound_port.ClientDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(outbound_port.ClientDatabasePort)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockDatabasePortMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockDatabasePort)(nil).Client))
}

// Customer mocks base method.
func (m *MockDatabasePort) Customer() outbound_port.CustomerDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Customer")
	ret0, _ := ret[0].(outbound_port.CustomerDatabasePort)
	return ret0
}

// Customer indicates an expected call of Customer.
func (mr *MockDatabasePortMockRecorder) Customer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Customer", reflect.TypeOf((*MockDatabasePort)(nil).Customer))
}

// DoInTransaction mocks base method.
func (m *MockDatabasePort) DoInTransaction(ctx context.Context, txFunc outbound_port.InTransaction) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoInTransaction", ctx, txFunc)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoInTransaction indicates an expected call of DoInTransaction.
func (mr *MockDatabasePortMockRecorder) DoInTransaction(ctx, txFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoInTransaction", reflect.TypeOf((*MockDatabasePort)(nil).DoInTransaction), ctx, txFunc)
}

// Mikrotik mocks base method.
func (m *MockDatabasePort) Mikrotik() outbound_port.MikrotikDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mikrotik")
	ret0, _ := ret[0].(outbound_port.MikrotikDatabasePort)
	return ret0
}

// Mikrotik indicates an expected call of Mikrotik.
func (mr *MockDatabasePortMockRecorder) Mikrotik() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mikrotik", reflect.TypeOf((*MockDatabasePort)(nil).Mikrotik))
}

// Profile mocks base method.
func (m *MockDatabasePort) Profile() outbound_port.ProfileDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile")
	ret0, _ := ret[0].(outbound_port.ProfileDatabasePort)
	return ret0
}

// Profile indicates an expected call of Profile.
func (mr *MockDatabasePortMockRecorder) Profile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockDatabasePort)(nil).Profile))
}

// Tenant mocks base method.
func (m *MockDatabasePort) Tenant() outbound_port.TenantDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tenant")
	ret0, _ := ret[0].(outbound_port.TenantDatabasePort)
	return ret0
}

// Tenant indicates an expected call of Tenant.
func (mr *MockDatabasePortMockRecorder) Tenant() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tenant", reflect.TypeOf((*MockDatabasePort)(nil).Tenant))
}

// TenantUser mocks base method.
func (m *MockDatabasePort) TenantUser() outbound_port.TenantUserDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TenantUser")
	ret0, _ := ret[0].(outbound_port.TenantUserDatabasePort)
	return ret0
}

// TenantUser indicates an expected call of TenantUser.
func (mr *MockDatabasePortMockRecorder) TenantUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TenantUser", reflect.TypeOf((*MockDatabasePort)(nil).TenantUser))
}

// User mocks base method.
func (m *MockDatabasePort) User() outbound_port.UserDatabasePort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(outbound_port.UserDatabasePort)
	return ret0
}

// User indicates an expected call of User.
func (mr *MockDatabasePortMockRecorder) User() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockDatabasePort)(nil).User))
}
