// Code generated by MockGen. DO NOT EDIT.
// Source: provisioning.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "MikrOps/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockProvisioningMessagePort is a mock of ProvisioningMessagePort interface.
type MockProvisioningMessagePort struct {
	ctrl     *gomock.Controller
	recorder *MockProvisioningMessagePortMockRecorder
}

// MockProvisioningMessagePortMockRecorder is the mock recorder for MockProvisioningMessagePort.
type MockProvisioningMessagePortMockRecorder struct {
	mock *MockProvisioningMessagePort
}

// NewMockProvisioningMessagePort creates a new mock instance.
func NewMockProvisioningMessagePort(ctrl *gomock.Controller) *MockProvisioningMessagePort {
	mock := &MockProvisioningMessagePort{ctrl: ctrl}
	mock.recorder = &MockProvisioningMessagePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvisioningMessagePort) EXPECT() *MockProvisioningMessagePortMockRecorder {
	return m.recorder
}

// PublishDisconnect mocks base method.
func (m *MockProvisioningMessagePort) PublishDisconnect(ctx context.Context, msg model.DisconnectMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishDisconnect", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishDisconnect indicates an expected call of PublishDisconnect.
func (mr *MockProvisioningMessagePortMockRecorder) PublishDisconnect(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishDisconnect", reflect.TypeOf((*MockProvisioningMessagePort)(nil).PublishDisconnect), ctx, msg)
}

// PublishProvisioning mocks base method.
func (m *MockProvisioningMessagePort) PublishProvisioning(ctx context.Context, msg model.ProvisioningMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProvisioning", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishProvisioning indicates an expected call of PublishProvisioning.
func (mr *MockProvisioningMessagePortMockRecorder) PublishProvisioning(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProvisioning", reflect.TypeOf((*MockProvisioningMessagePort)(nil).PublishProvisioning), ctx, msg)
}
