// Code generated by MockGen. DO NOT EDIT.
// Source: mikrotik.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "prabogo/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockMikrotikDatabasePort is a mock of MikrotikDatabasePort interface.
type MockMikrotikDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockMikrotikDatabasePortMockRecorder
}

// MockMikrotikDatabasePortMockRecorder is the mock recorder for MockMikrotikDatabasePort.
type MockMikrotikDatabasePortMockRecorder struct {
	mock *MockMikrotikDatabasePort
}

// NewMockMikrotikDatabasePort creates a new mock instance.
func NewMockMikrotikDatabasePort(ctrl *gomock.Controller) *MockMikrotikDatabasePort {
	mock := &MockMikrotikDatabasePort{ctrl: ctrl}
	mock.recorder = &MockMikrotikDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMikrotikDatabasePort) EXPECT() *MockMikrotikDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMikrotikDatabasePort) Create(tenantID uuid.UUID, input model.MikrotikInput) (*model.Mikrotik, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", tenantID, input)
	ret0, _ := ret[0].(*model.Mikrotik)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMikrotikDatabasePortMockRecorder) Create(tenantID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).Create), tenantID, input)
}

// DeactivateAll mocks base method.
func (m *MockMikrotikDatabasePort) DeactivateAll(tenantID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateAll", tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateAll indicates an expected call of DeactivateAll.
func (mr *MockMikrotikDatabasePortMockRecorder) DeactivateAll(tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateAll", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).DeactivateAll), tenantID)
}

// Delete mocks base method.
func (m *MockMikrotikDatabasePort) Delete(tenantID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMikrotikDatabasePortMockRecorder) Delete(tenantID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).Delete), tenantID, id)
}

// GetActiveMikrotik mocks base method.
func (m *MockMikrotikDatabasePort) GetActiveMikrotik(tenantID uuid.UUID) (*model.Mikrotik, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveMikrotik", tenantID)
	ret0, _ := ret[0].(*model.Mikrotik)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveMikrotik indicates an expected call of GetActiveMikrotik.
func (mr *MockMikrotikDatabasePortMockRecorder) GetActiveMikrotik(tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveMikrotik", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).GetActiveMikrotik), tenantID)
}

// GetByID mocks base method.
func (m *MockMikrotikDatabasePort) GetByID(tenantID, id uuid.UUID) (*model.Mikrotik, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", tenantID, id)
	ret0, _ := ret[0].(*model.Mikrotik)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMikrotikDatabasePortMockRecorder) GetByID(tenantID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).GetByID), tenantID, id)
}

// List mocks base method.
func (m *MockMikrotikDatabasePort) List(tenantID uuid.UUID, filter model.MikrotikFilter) ([]model.Mikrotik, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tenantID, filter)
	ret0, _ := ret[0].([]model.Mikrotik)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMikrotikDatabasePortMockRecorder) List(tenantID, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).List), tenantID, filter)
}

// SetActive mocks base method.
func (m *MockMikrotikDatabasePort) SetActive(tenantID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockMikrotikDatabasePortMockRecorder) SetActive(tenantID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).SetActive), tenantID, id)
}

// Update mocks base method.
func (m *MockMikrotikDatabasePort) Update(tenantID, id uuid.UUID, input model.MikrotikUpdateInput) (*model.Mikrotik, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tenantID, id, input)
	ret0, _ := ret[0].(*model.Mikrotik)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMikrotikDatabasePortMockRecorder) Update(tenantID, id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).Update), tenantID, id, input)
}

// UpdateLastSync mocks base method.
func (m *MockMikrotikDatabasePort) UpdateLastSync(tenantID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastSync", tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastSync indicates an expected call of UpdateLastSync.
func (mr *MockMikrotikDatabasePortMockRecorder) UpdateLastSync(tenantID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastSync", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).UpdateLastSync), tenantID, id)
}

// UpdateStatus mocks base method.
func (m *MockMikrotikDatabasePort) UpdateStatus(tenantID, id uuid.UUID, status model.MikrotikStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", tenantID, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockMikrotikDatabasePortMockRecorder) UpdateStatus(tenantID, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).UpdateStatus), tenantID, id, status)
}
