// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/outbound/tenant.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "MikrOps/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTenantDatabasePort is a mock of TenantDatabasePort interface.
type MockTenantDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockTenantDatabasePortMockRecorder
}

// MockTenantDatabasePortMockRecorder is the mock recorder for MockTenantDatabasePort.
type MockTenantDatabasePortMockRecorder struct {
	mock *MockTenantDatabasePort
}

// NewMockTenantDatabasePort creates a new mock instance.
func NewMockTenantDatabasePort(ctrl *gomock.Controller) *MockTenantDatabasePort {
	mock := &MockTenantDatabasePort{ctrl: ctrl}
	mock.recorder = &MockTenantDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantDatabasePort) EXPECT() *MockTenantDatabasePortMockRecorder {
	return m.recorder
}

// CreateTenant mocks base method.
func (m *MockTenantDatabasePort) CreateTenant(input model.TenantInput) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", input)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockTenantDatabasePortMockRecorder) CreateTenant(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockTenantDatabasePort)(nil).CreateTenant), input)
}

// Delete mocks base method.
func (m *MockTenantDatabasePort) Delete(id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret1, _ := ret[0].(error)
	return ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantDatabasePortMockRecorder) Delete(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantDatabasePort)(nil).Delete), id)
}

// GetByID mocks base method.
func (m *MockTenantDatabasePort) GetByID(id uuid.UUID) (*model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", id)
	ret0, _ := ret[0].(*model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTenantDatabasePortMockRecorder) GetByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTenantDatabasePort)(nil).GetByID), id)
}

// GetStats mocks base method.
func (m *MockTenantDatabasePort) GetStats(tenantID uuid.UUID) (*model.TenantStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", tenantID)
	ret0, _ := ret[0].(*model.TenantStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockTenantDatabasePortMockRecorder) GetStats(tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockTenantDatabasePort)(nil).GetStats), tenantID)
}

// List mocks base method.
func (m *MockTenantDatabasePort) List(filter model.TenantFilter) ([]model.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", filter)
	ret0, _ := ret[0].([]model.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTenantDatabasePortMockRecorder) List(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTenantDatabasePort)(nil).List), filter)
}

// Update mocks base method.
func (m *MockTenantDatabasePort) Update(id uuid.UUID, input model.TenantInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", id, input)
	ret1, _ := ret[0].(error)
	return ret1
}

// Update indicates an expected call of Update.
func (mr *MockTenantDatabasePortMockRecorder) Update(id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantDatabasePort)(nil).Update), id, input)
}

