// Code generated by MockGen. DO NOT EDIT.
// Source: profile.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "prabogo/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockProfileDatabasePort is a mock of ProfileDatabasePort interface.
type MockProfileDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockProfileDatabasePortMockRecorder
}

// MockProfileDatabasePortMockRecorder is the mock recorder for MockProfileDatabasePort.
type MockProfileDatabasePortMockRecorder struct {
	mock *MockProfileDatabasePort
}

// NewMockProfileDatabasePort creates a new mock instance.
func NewMockProfileDatabasePort(ctrl *gomock.Controller) *MockProfileDatabasePort {
	mock := &MockProfileDatabasePort{ctrl: ctrl}
	mock.recorder = &MockProfileDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileDatabasePort) EXPECT() *MockProfileDatabasePortMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockProfileDatabasePort) CreateProfile(tenantID uuid.UUID, input model.ProfileInput, mikrotikID uuid.UUID) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", tenantID, input, mikrotikID)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockProfileDatabasePortMockRecorder) CreateProfile(tenantID, input, mikrotikID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockProfileDatabasePort)(nil).CreateProfile), tenantID, input, mikrotikID)
}

// CreateProfilePPPoE mocks base method.
func (m *MockProfileDatabasePort) CreateProfilePPPoE(tenantID, profileID uuid.UUID, input model.ProfileInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfilePPPoE", tenantID, profileID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProfilePPPoE indicates an expected call of CreateProfilePPPoE.
func (mr *MockProfileDatabasePortMockRecorder) CreateProfilePPPoE(tenantID, profileID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfilePPPoE", reflect.TypeOf((*MockProfileDatabasePort)(nil).CreateProfilePPPoE), tenantID, profileID, input)
}

// Delete mocks base method.
func (m *MockProfileDatabasePort) Delete(tenantID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", tenantID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProfileDatabasePortMockRecorder) Delete(tenantID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProfileDatabasePort)(nil).Delete), tenantID, id)
}

// GetByID mocks base method.
func (m *MockProfileDatabasePort) GetByID(tenantID, id uuid.UUID) (*model.ProfileWithPPPoE, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", tenantID, id)
	ret0, _ := ret[0].(*model.ProfileWithPPPoE)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProfileDatabasePortMockRecorder) GetByID(tenantID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProfileDatabasePort)(nil).GetByID), tenantID, id)
}

// GetByMikrotikID mocks base method.
func (m *MockProfileDatabasePort) GetByMikrotikID(tenantID, mikrotikID, profileID uuid.UUID) (*model.ProfileWithPPPoE, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMikrotikID", tenantID, mikrotikID, profileID)
	ret0, _ := ret[0].(*model.ProfileWithPPPoE)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMikrotikID indicates an expected call of GetByMikrotikID.
func (mr *MockProfileDatabasePortMockRecorder) GetByMikrotikID(tenantID, mikrotikID, profileID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMikrotikID", reflect.TypeOf((*MockProfileDatabasePort)(nil).GetByMikrotikID), tenantID, mikrotikID, profileID)
}

// List mocks base method.
func (m *MockProfileDatabasePort) List(tenantID, mikrotikID uuid.UUID) ([]model.ProfileWithPPPoE, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", tenantID, mikrotikID)
	ret0, _ := ret[0].([]model.ProfileWithPPPoE)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProfileDatabasePortMockRecorder) List(tenantID, mikrotikID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProfileDatabasePort)(nil).List), tenantID, mikrotikID)
}

// Update mocks base method.
func (m *MockProfileDatabasePort) Update(tenantID, id uuid.UUID, input model.ProfileInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", tenantID, id, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockProfileDatabasePortMockRecorder) Update(tenantID, id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProfileDatabasePort)(nil).Update), tenantID, id, input)
}

// UpdateMikrotikObjectID mocks base method.
func (m *MockProfileDatabasePort) UpdateMikrotikObjectID(tenantID, profileID uuid.UUID, objectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMikrotikObjectID", tenantID, profileID, objectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMikrotikObjectID indicates an expected call of UpdateMikrotikObjectID.
func (mr *MockProfileDatabasePortMockRecorder) UpdateMikrotikObjectID(tenantID, profileID, objectID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMikrotikObjectID", reflect.TypeOf((*MockProfileDatabasePort)(nil).UpdateMikrotikObjectID), tenantID, profileID, objectID)
}
