// Code generated by MockGen. DO NOT EDIT.
// Source: mikrotik_client.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "MikrOps/internal/model"
	outbound_port "MikrOps/internal/port/outbound"
	reflect "reflect"

	routeros "github.com/go-routeros/routeros/v3"
	proto "github.com/go-routeros/routeros/v3/proto"
	gomock "github.com/golang/mock/gomock"
)

// MockMikrotikClientPort is a mock of MikrotikClientPort interface.
type MockMikrotikClientPort struct {
	ctrl     *gomock.Controller
	recorder *MockMikrotikClientPortMockRecorder
}

// MockMikrotikClientPortMockRecorder is the mock recorder for MockMikrotikClientPort.
type MockMikrotikClientPortMockRecorder struct {
	mock *MockMikrotikClientPort
}

// NewMockMikrotikClientPort creates a new mock instance.
func NewMockMikrotikClientPort(ctrl *gomock.Controller) *MockMikrotikClientPort {
	mock := &MockMikrotikClientPort{ctrl: ctrl}
	mock.recorder = &MockMikrotikClientPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMikrotikClientPort) EXPECT() *MockMikrotikClientPortMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMikrotikClientPort) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMikrotikClientPortMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMikrotikClientPort)(nil).Close))
}

// ListenArgs mocks base method.
func (m *MockMikrotikClientPort) ListenArgs(sentence string, args map[string]string) (<-chan *proto.Sentence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenArgs", sentence, args)
	ret0, _ := ret[0].(<-chan *proto.Sentence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListenArgs indicates an expected call of ListenArgs.
func (mr *MockMikrotikClientPortMockRecorder) ListenArgs(sentence, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenArgs", reflect.TypeOf((*MockMikrotikClientPort)(nil).ListenArgs), sentence, args)
}

// Run mocks base method.
func (m *MockMikrotikClientPort) Run(sentence ...string) (*routeros.Reply, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range sentence {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Run", varargs...)
	ret0, _ := ret[0].(*routeros.Reply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockMikrotikClientPortMockRecorder) Run(sentence ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockMikrotikClientPort)(nil).Run), sentence...)
}

// RunArgs mocks base method.
func (m *MockMikrotikClientPort) RunArgs(sentence string, args map[string]string) (*routeros.Reply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunArgs", sentence, args)
	ret0, _ := ret[0].(*routeros.Reply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunArgs indicates an expected call of RunArgs.
func (mr *MockMikrotikClientPortMockRecorder) RunArgs(sentence, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunArgs", reflect.TypeOf((*MockMikrotikClientPort)(nil).RunArgs), sentence, args)
}

// MockMikrotikClientFactory is a mock of MikrotikClientFactory interface.
type MockMikrotikClientFactory struct {
	ctrl     *gomock.Controller
	recorder *MockMikrotikClientFactoryMockRecorder
}

// MockMikrotikClientFactoryMockRecorder is the mock recorder for MockMikrotikClientFactory.
type MockMikrotikClientFactoryMockRecorder struct {
	mock *MockMikrotikClientFactory
}

// NewMockMikrotikClientFactory creates a new mock instance.
func NewMockMikrotikClientFactory(ctrl *gomock.Controller) *MockMikrotikClientFactory {
	mock := &MockMikrotikClientFactory{ctrl: ctrl}
	mock.recorder = &MockMikrotikClientFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMikrotikClientFactory) EXPECT() *MockMikrotikClientFactoryMockRecorder {
	return m.recorder
}

// NewClient mocks base method.
func (m *MockMikrotikClientFactory) NewClient(mikrotik *model.Mikrotik) (outbound_port.MikrotikClientPort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClient", mikrotik)
	ret0, _ := ret[0].(outbound_port.MikrotikClientPort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewClient indicates an expected call of NewClient.
func (mr *MockMikrotikClientFactoryMockRecorder) NewClient(mikrotik interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockMikrotikClientFactory)(nil).NewClient), mikrotik)
}

