// Code generated by MockGen. DO NOT EDIT.
// Source: jwt_port.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJWTPort is a mock of JWTPort interface.
type MockJWTPort struct {
	ctrl     *gomock.Controller
	recorder *MockJWTPortMockRecorder
}

// MockJWTPortMockRecorder is the mock recorder for MockJWTPort.
type MockJWTPortMockRecorder struct {
	mock *MockJWTPort
}

// NewMockJWTPort creates a new mock instance.
func NewMockJWTPort(ctrl *gomock.Controller) *MockJWTPort {
	mock := &MockJWTPort{ctrl: ctrl}
	mock.recorder = &MockJWTPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTPort) EXPECT() *MockJWTPortMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockJWTPort) GenerateAccessToken(ctx context.Context, userID, username, role string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", ctx, userID, username, role)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockJWTPortMockRecorder) GenerateAccessToken(ctx, userID, username, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockJWTPort)(nil).GenerateAccessToken), ctx, userID, username, role)
}

// ParseToken mocks base method.
func (m *MockJWTPort) ParseToken(tokenString string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseToken", tokenString)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseToken indicates an expected call of ParseToken.
func (mr *MockJWTPortMockRecorder) ParseToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseToken", reflect.TypeOf((*MockJWTPort)(nil).ParseToken), tokenString)
}

// ValidateToken mocks base method.
func (m *MockJWTPort) ValidateToken(ctx context.Context, tokenString string) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, tokenString)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockJWTPortMockRecorder) ValidateToken(ctx, tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockJWTPort)(nil).ValidateToken), ctx, tokenString)
}
