// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "prabogo/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAuthDatabasePort is a mock of AuthDatabasePort interface.
type MockAuthDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockAuthDatabasePortMockRecorder
}

// MockAuthDatabasePortMockRecorder is the mock recorder for MockAuthDatabasePort.
type MockAuthDatabasePortMockRecorder struct {
	mock *MockAuthDatabasePort
}

// NewMockAuthDatabasePort creates a new mock instance.
func NewMockAuthDatabasePort(ctrl *gomock.Controller) *MockAuthDatabasePort {
	mock := &MockAuthDatabasePort{ctrl: ctrl}
	mock.recorder = &MockAuthDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthDatabasePort) EXPECT() *MockAuthDatabasePortMockRecorder {
	return m.recorder
}

// FindRoleByID mocks base method.
func (m *MockAuthDatabasePort) FindRoleByID(id uuid.UUID) (*model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoleByID", id)
	ret0, _ := ret[0].(*model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoleByID indicates an expected call of FindRoleByID.
func (mr *MockAuthDatabasePortMockRecorder) FindRoleByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoleByID", reflect.TypeOf((*MockAuthDatabasePort)(nil).FindRoleByID), id)
}

// FindRoleByName mocks base method.
func (m *MockAuthDatabasePort) FindRoleByName(name string) (*model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRoleByName", name)
	ret0, _ := ret[0].(*model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRoleByName indicates an expected call of FindRoleByName.
func (mr *MockAuthDatabasePortMockRecorder) FindRoleByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRoleByName", reflect.TypeOf((*MockAuthDatabasePort)(nil).FindRoleByName), name)
}

// FindUserByFilter mocks base method.
func (m *MockAuthDatabasePort) FindUserByFilter(filter model.UserFilter, lock bool) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByFilter", filter, lock)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByFilter indicates an expected call of FindUserByFilter.
func (mr *MockAuthDatabasePortMockRecorder) FindUserByFilter(filter, lock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByFilter", reflect.TypeOf((*MockAuthDatabasePort)(nil).FindUserByFilter), filter, lock)
}

// SaveUser mocks base method.
func (m *MockAuthDatabasePort) SaveUser(user model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockAuthDatabasePortMockRecorder) SaveUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockAuthDatabasePort)(nil).SaveUser), user)
}
