// Code generated by MockGen. DO NOT EDIT.
// Source: tenant_user.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockTenantUserDatabasePort is a mock of TenantUserDatabasePort interface.
type MockTenantUserDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockTenantUserDatabasePortMockRecorder
}

// MockTenantUserDatabasePortMockRecorder is the mock recorder for MockTenantUserDatabasePort.
type MockTenantUserDatabasePortMockRecorder struct {
	mock *MockTenantUserDatabasePort
}

// NewMockTenantUserDatabasePort creates a new mock instance.
func NewMockTenantUserDatabasePort(ctrl *gomock.Controller) *MockTenantUserDatabasePort {
	mock := &MockTenantUserDatabasePort{ctrl: ctrl}
	mock.recorder = &MockTenantUserDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantUserDatabasePort) EXPECT() *MockTenantUserDatabasePortMockRecorder {
	return m.recorder
}

// AssignUserToTenant mocks base method.
func (m *MockTenantUserDatabasePort) AssignUserToTenant(ctx context.Context, userID, tenantID uuid.UUID, roleID *uuid.UUID, isPrimary bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignUserToTenant", ctx, userID, tenantID, roleID, isPrimary)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignUserToTenant indicates an expected call of AssignUserToTenant.
func (mr *MockTenantUserDatabasePortMockRecorder) AssignUserToTenant(ctx, userID, tenantID, roleID, isPrimary interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignUserToTenant", reflect.TypeOf((*MockTenantUserDatabasePort)(nil).AssignUserToTenant), ctx, userID, tenantID, roleID, isPrimary)
}

// GetPrimaryTenant mocks base method.
func (m *MockTenantUserDatabasePort) GetPrimaryTenant(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrimaryTenant", ctx, userID)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrimaryTenant indicates an expected call of GetPrimaryTenant.
func (mr *MockTenantUserDatabasePortMockRecorder) GetPrimaryTenant(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrimaryTenant", reflect.TypeOf((*MockTenantUserDatabasePort)(nil).GetPrimaryTenant), ctx, userID)
}

// GetTenantsForUser mocks base method.
func (m *MockTenantUserDatabasePort) GetTenantsForUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenantsForUser", ctx, userID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenantsForUser indicates an expected call of GetTenantsForUser.
func (mr *MockTenantUserDatabasePortMockRecorder) GetTenantsForUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenantsForUser", reflect.TypeOf((*MockTenantUserDatabasePort)(nil).GetTenantsForUser), ctx, userID)
}

// HasAccess mocks base method.
func (m *MockTenantUserDatabasePort) HasAccess(ctx context.Context, userID, tenantID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAccess", ctx, userID, tenantID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasAccess indicates an expected call of HasAccess.
func (mr *MockTenantUserDatabasePortMockRecorder) HasAccess(ctx, userID, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAccess", reflect.TypeOf((*MockTenantUserDatabasePort)(nil).HasAccess), ctx, userID, tenantID)
}
