// Code generated by MockGen. DO NOT EDIT.
// Source: mikrotik.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "MikrOps/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockMikrotikDatabasePort is a mock of MikrotikDatabasePort interface.
type MockMikrotikDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockMikrotikDatabasePortMockRecorder
}

// MockMikrotikDatabasePortMockRecorder is the mock recorder for MockMikrotikDatabasePort.
type MockMikrotikDatabasePortMockRecorder struct {
	mock *MockMikrotikDatabasePort
}

// NewMockMikrotikDatabasePort creates a new mock instance.
func NewMockMikrotikDatabasePort(ctrl *gomock.Controller) *MockMikrotikDatabasePort {
	mock := &MockMikrotikDatabasePort{ctrl: ctrl}
	mock.recorder = &MockMikrotikDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMikrotikDatabasePort) EXPECT() *MockMikrotikDatabasePortMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMikrotikDatabasePort) Create(ctx context.Context, input model.CreateMikrotikRequest) (*model.Mikrotik, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*model.Mikrotik)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMikrotikDatabasePortMockRecorder) Create(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).Create), ctx, input)
}

// DeactivateAll mocks base method.
func (m *MockMikrotikDatabasePort) DeactivateAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateAll indicates an expected call of DeactivateAll.
func (mr *MockMikrotikDatabasePortMockRecorder) DeactivateAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateAll", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).DeactivateAll), ctx)
}

// Delete mocks base method.
func (m *MockMikrotikDatabasePort) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockMikrotikDatabasePortMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).Delete), ctx, id)
}

// GetActiveMikrotik mocks base method.
func (m *MockMikrotikDatabasePort) GetActiveMikrotik(ctx context.Context) (*model.Mikrotik, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveMikrotik", ctx)
	ret0, _ := ret[0].(*model.Mikrotik)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveMikrotik indicates an expected call of GetActiveMikrotik.
func (mr *MockMikrotikDatabasePortMockRecorder) GetActiveMikrotik(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveMikrotik", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).GetActiveMikrotik), ctx)
}

// GetByID mocks base method.
func (m *MockMikrotikDatabasePort) GetByID(ctx context.Context, id uuid.UUID) (*model.Mikrotik, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Mikrotik)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMikrotikDatabasePortMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockMikrotikDatabasePort) List(ctx context.Context) ([]model.Mikrotik, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]model.Mikrotik)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMikrotikDatabasePortMockRecorder) List(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).List), ctx)
}

// SetActive mocks base method.
func (m *MockMikrotikDatabasePort) SetActive(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockMikrotikDatabasePortMockRecorder) SetActive(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).SetActive), ctx, id)
}

// Update mocks base method.
func (m *MockMikrotikDatabasePort) Update(ctx context.Context, id uuid.UUID, input model.UpdateMikrotikRequest) (*model.Mikrotik, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, input)
	ret0, _ := ret[0].(*model.Mikrotik)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockMikrotikDatabasePortMockRecorder) Update(ctx, id, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).Update), ctx, id, input)
}

// UpdateLastSync mocks base method.
func (m *MockMikrotikDatabasePort) UpdateLastSync(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastSync", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastSync indicates an expected call of UpdateLastSync.
func (mr *MockMikrotikDatabasePortMockRecorder) UpdateLastSync(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastSync", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).UpdateLastSync), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockMikrotikDatabasePort) UpdateStatus(ctx context.Context, id uuid.UUID, status model.MikrotikStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockMikrotikDatabasePortMockRecorder) UpdateStatus(ctx, id, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockMikrotikDatabasePort)(nil).UpdateStatus), ctx, id, status)
}
