// Code generated by MockGen. DO NOT EDIT.
// Source: redis_pubsub.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRedisPubSubPort is a mock of RedisPubSubPort interface.
type MockRedisPubSubPort struct {
	ctrl     *gomock.Controller
	recorder *MockRedisPubSubPortMockRecorder
}

// MockRedisPubSubPortMockRecorder is the mock recorder for MockRedisPubSubPort.
type MockRedisPubSubPortMockRecorder struct {
	mock *MockRedisPubSubPort
}

// NewMockRedisPubSubPort creates a new mock instance.
func NewMockRedisPubSubPort(ctrl *gomock.Controller) *MockRedisPubSubPort {
	mock := &MockRedisPubSubPort{ctrl: ctrl}
	mock.recorder = &MockRedisPubSubPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisPubSubPort) EXPECT() *MockRedisPubSubPortMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockRedisPubSubPort) Publish(channel, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", channel, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockRedisPubSubPortMockRecorder) Publish(channel, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockRedisPubSubPort)(nil).Publish), channel, message)
}
