// Code generated by MockGen. DO NOT EDIT.
// Source: auth_cache.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "MikrOps/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthCachePort is a mock of AuthCachePort interface.
type MockAuthCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockAuthCachePortMockRecorder
}

// MockAuthCachePortMockRecorder is the mock recorder for MockAuthCachePort.
type MockAuthCachePortMockRecorder struct {
	mock *MockAuthCachePort
}

// NewMockAuthCachePort creates a new mock instance.
func NewMockAuthCachePort(ctrl *gomock.Controller) *MockAuthCachePort {
	mock := &MockAuthCachePort{ctrl: ctrl}
	mock.recorder = &MockAuthCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthCachePort) EXPECT() *MockAuthCachePortMockRecorder {
	return m.recorder
}

// GetRefreshTokenMetadata mocks base method.
func (m *MockAuthCachePort) GetRefreshTokenMetadata(ctx context.Context, tokenHash string) (*model.RefreshTokenMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTokenMetadata", ctx, tokenHash)
	ret0, _ := ret[0].(*model.RefreshTokenMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefreshTokenMetadata indicates an expected call of GetRefreshTokenMetadata.
func (mr *MockAuthCachePortMockRecorder) GetRefreshTokenMetadata(ctx, tokenHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTokenMetadata", reflect.TypeOf((*MockAuthCachePort)(nil).GetRefreshTokenMetadata), ctx, tokenHash)
}

// InvalidateAllUserTokens mocks base method.
func (m *MockAuthCachePort) InvalidateAllUserTokens(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateAllUserTokens", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateAllUserTokens indicates an expected call of InvalidateAllUserTokens.
func (mr *MockAuthCachePortMockRecorder) InvalidateAllUserTokens(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAllUserTokens", reflect.TypeOf((*MockAuthCachePort)(nil).InvalidateAllUserTokens), ctx, userID)
}

// InvalidateToken mocks base method.
func (m *MockAuthCachePort) InvalidateToken(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateToken", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateToken indicates an expected call of InvalidateToken.
func (mr *MockAuthCachePortMockRecorder) InvalidateToken(ctx, tokenHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateToken", reflect.TypeOf((*MockAuthCachePort)(nil).InvalidateToken), ctx, tokenHash)
}

// IsTokenRotated mocks base method.
func (m *MockAuthCachePort) IsTokenRotated(ctx context.Context, tokenHash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenRotated", ctx, tokenHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTokenRotated indicates an expected call of IsTokenRotated.
func (mr *MockAuthCachePortMockRecorder) IsTokenRotated(ctx, tokenHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenRotated", reflect.TypeOf((*MockAuthCachePort)(nil).IsTokenRotated), ctx, tokenHash)
}

// MarkTokenRotated mocks base method.
func (m *MockAuthCachePort) MarkTokenRotated(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTokenRotated", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTokenRotated indicates an expected call of MarkTokenRotated.
func (mr *MockAuthCachePortMockRecorder) MarkTokenRotated(ctx, tokenHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTokenRotated", reflect.TypeOf((*MockAuthCachePort)(nil).MarkTokenRotated), ctx, tokenHash)
}

// MarkTokenUsed mocks base method.
func (m *MockAuthCachePort) MarkTokenUsed(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTokenUsed", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTokenUsed indicates an expected call of MarkTokenUsed.
func (mr *MockAuthCachePortMockRecorder) MarkTokenUsed(ctx, tokenHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTokenUsed", reflect.TypeOf((*MockAuthCachePort)(nil).MarkTokenUsed), ctx, tokenHash)
}

// StoreRefreshToken mocks base method.
func (m *MockAuthCachePort) StoreRefreshToken(ctx context.Context, metadata model.RefreshTokenMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRefreshToken", ctx, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRefreshToken indicates an expected call of StoreRefreshToken.
func (mr *MockAuthCachePortMockRecorder) StoreRefreshToken(ctx, metadata interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRefreshToken", reflect.TypeOf((*MockAuthCachePort)(nil).StoreRefreshToken), ctx, metadata)
}
