// Code generated by MockGen. DO NOT EDIT.
// Source: password_hasher_port.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPasswordHasherPort is a mock of PasswordHasherPort interface.
type MockPasswordHasherPort struct {
	ctrl     *gomock.Controller
	recorder *MockPasswordHasherPortMockRecorder
}

// MockPasswordHasherPortMockRecorder is the mock recorder for MockPasswordHasherPort.
type MockPasswordHasherPortMockRecorder struct {
	mock *MockPasswordHasherPort
}

// NewMockPasswordHasherPort creates a new mock instance.
func NewMockPasswordHasherPort(ctrl *gomock.Controller) *MockPasswordHasherPort {
	mock := &MockPasswordHasherPort{ctrl: ctrl}
	mock.recorder = &MockPasswordHasherPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasswordHasherPort) EXPECT() *MockPasswordHasherPortMockRecorder {
	return m.recorder
}

// GenerateRandomToken mocks base method.
func (m *MockPasswordHasherPort) GenerateRandomToken(length int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRandomToken", length)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateRandomToken indicates an expected call of GenerateRandomToken.
func (mr *MockPasswordHasherPortMockRecorder) GenerateRandomToken(length interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRandomToken", reflect.TypeOf((*MockPasswordHasherPort)(nil).GenerateRandomToken), length)
}

// HashPassword mocks base method.
func (m *MockPasswordHasherPort) HashPassword(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockPasswordHasherPortMockRecorder) HashPassword(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockPasswordHasherPort)(nil).HashPassword), password)
}

// VerifyPassword mocks base method.
func (m *MockPasswordHasherPort) VerifyPassword(hashedPassword, password string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPassword", hashedPassword, password)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyPassword indicates an expected call of VerifyPassword.
func (mr *MockPasswordHasherPortMockRecorder) VerifyPassword(hashedPassword, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPassword", reflect.TypeOf((*MockPasswordHasherPort)(nil).VerifyPassword), hashedPassword, password)
}
