// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_outbound_port is a generated GoMock package.
package mock_outbound_port

import (
	model "MikrOps/internal/model"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClientDatabasePort is a mock of ClientDatabasePort interface.
type MockClientDatabasePort struct {
	ctrl     *gomock.Controller
	recorder *MockClientDatabasePortMockRecorder
}

// MockClientDatabasePortMockRecorder is the mock recorder for MockClientDatabasePort.
type MockClientDatabasePortMockRecorder struct {
	mock *MockClientDatabasePort
}

// NewMockClientDatabasePort creates a new mock instance.
func NewMockClientDatabasePort(ctrl *gomock.Controller) *MockClientDatabasePort {
	mock := &MockClientDatabasePort{ctrl: ctrl}
	mock.recorder = &MockClientDatabasePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientDatabasePort) EXPECT() *MockClientDatabasePortMockRecorder {
	return m.recorder
}

// DeleteByFilter mocks base method.
func (m *MockClientDatabasePort) DeleteByFilter(ctx context.Context, filter model.ClientFilter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByFilter", ctx, filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByFilter indicates an expected call of DeleteByFilter.
func (mr *MockClientDatabasePortMockRecorder) DeleteByFilter(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByFilter", reflect.TypeOf((*MockClientDatabasePort)(nil).DeleteByFilter), ctx, filter)
}

// FindByFilter mocks base method.
func (m *MockClientDatabasePort) FindByFilter(ctx context.Context, filter model.ClientFilter, lock bool) ([]model.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", ctx, filter, lock)
	ret0, _ := ret[0].([]model.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter.
func (mr *MockClientDatabasePortMockRecorder) FindByFilter(ctx, filter, lock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockClientDatabasePort)(nil).FindByFilter), ctx, filter, lock)
}

// IsExists mocks base method.
func (m *MockClientDatabasePort) IsExists(ctx context.Context, bearerKey string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExists", ctx, bearerKey)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExists indicates an expected call of IsExists.
func (mr *MockClientDatabasePortMockRecorder) IsExists(ctx, bearerKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExists", reflect.TypeOf((*MockClientDatabasePort)(nil).IsExists), ctx, bearerKey)
}

// Upsert mocks base method.
func (m *MockClientDatabasePort) Upsert(ctx context.Context, datas []model.ClientInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, datas)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockClientDatabasePortMockRecorder) Upsert(ctx, datas interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockClientDatabasePort)(nil).Upsert), ctx, datas)
}

// MockClientMessagePort is a mock of ClientMessagePort interface.
type MockClientMessagePort struct {
	ctrl     *gomock.Controller
	recorder *MockClientMessagePortMockRecorder
}

// MockClientMessagePortMockRecorder is the mock recorder for MockClientMessagePort.
type MockClientMessagePortMockRecorder struct {
	mock *MockClientMessagePort
}

// NewMockClientMessagePort creates a new mock instance.
func NewMockClientMessagePort(ctrl *gomock.Controller) *MockClientMessagePort {
	mock := &MockClientMessagePort{ctrl: ctrl}
	mock.recorder = &MockClientMessagePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientMessagePort) EXPECT() *MockClientMessagePortMockRecorder {
	return m.recorder
}

// PublishUpsert mocks base method.
func (m *MockClientMessagePort) PublishUpsert(ctx context.Context, datas []model.ClientInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUpsert", ctx, datas)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishUpsert indicates an expected call of PublishUpsert.
func (mr *MockClientMessagePortMockRecorder) PublishUpsert(ctx, datas interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUpsert", reflect.TypeOf((*MockClientMessagePort)(nil).PublishUpsert), ctx, datas)
}

// MockClientCachePort is a mock of ClientCachePort interface.
type MockClientCachePort struct {
	ctrl     *gomock.Controller
	recorder *MockClientCachePortMockRecorder
}

// MockClientCachePortMockRecorder is the mock recorder for MockClientCachePort.
type MockClientCachePortMockRecorder struct {
	mock *MockClientCachePort
}

// NewMockClientCachePort creates a new mock instance.
func NewMockClientCachePort(ctrl *gomock.Controller) *MockClientCachePort {
	mock := &MockClientCachePort{ctrl: ctrl}
	mock.recorder = &MockClientCachePortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientCachePort) EXPECT() *MockClientCachePortMockRecorder {
	return m.recorder
}

// GetClient mocks base method.
func (m *MockClientCachePort) GetClient(ctx context.Context, bearerKey string) (model.Client, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, bearerKey)
	ret0, _ := ret[0].(model.Client)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClientCachePortMockRecorder) GetClient(ctx, bearerKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClientCachePort)(nil).GetClient), ctx, bearerKey)
}

// SetClient mocks base method.
func (m *MockClientCachePort) SetClient(ctx context.Context, bearerKey string, client model.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetClient", ctx, bearerKey, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetClient indicates an expected call of SetClient.
func (mr *MockClientCachePortMockRecorder) SetClient(ctx, bearerKey, client interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClient", reflect.TypeOf((*MockClientCachePort)(nil).SetClient), ctx, bearerKey, client)
}
