### Base URL
@baseUrl = http://localhost:8000
@adminUsername = superadmin@mikrobill.com
@adminPassword = password123
@roleId = c5a9e294-2917-4530-b56b-164b2e145e30

### 1. Login User
# @name login
POST {{baseUrl}}/v1/auth/login
Content-Type: application/json

{
  "username": "{{adminUsername}}",
  "password": "{{adminPassword}}"
}

> {%
    client.global.set("authToken", response.body.data.api_token);
    client.global.set("roleId", response.body.data.role_id);
%}

### 2. Register New User
POST {{baseUrl}}/v1/auth/register
Content-Type: application/json

{
  "username": "newuser",
  "email": "newuser@example.com",
  "password": "SecurePass123!",
  "fullname": "New User",
  "phone": "081234567890"
}