### Base URL
@baseUrl = http://localhost:8080
@clientKey = internal
@mikrotikId = e5a065c0-1d00-41e9-b4c3-c87ef7f8da28
@pppSecretId = 

### 1. Create PPP Secret
# @name createPppSecret
POST {{baseUrl}}/v1/internal/ppp/secret
Content-Type: application/json
X-Client-Key: {{clientKey}}

{
  "name": "testuser1",
  "password": "testpassword123",
  "service": "pppoe",
  "profile": "default",
  "local_address": "10.0.0.1",
  "remote_address": "10.0.0.100",
  "comment": "Test PPPoE user"
}

> {%
    client.global.set("pppSecretId", response.body.data.id);
%}

### 2. Get PPP Secret by ID
GET {{baseUrl}}/v1/internal/ppp/secret/{{pppSecretId}}
X-Client-Key: {{clientKey}}

### 3. Update PPP Secret
PUT {{baseUrl}}/v1/internal/ppp/secret/{{pppSecretId}}
Content-Type: application/json
X-Client-Key: {{clientKey}}

{
  "password": "newpassword456",
  "profile": "premium",
  "comment": "Updated test user",
  "disabled": false
}

### 4. List All PPP Secrets
GET {{baseUrl}}/v1/internal/ppp/secret/list
X-Client-Key: {{clientKey}}

### 5. Delete PPP Secret
DELETE {{baseUrl}}/v1/internal/ppp/secret/{{pppSecretId}}
X-Client-Key: {{clientKey}}