### Base URL
@baseUrl = http://localhost:8000
@clientKey = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Njg3MTE1NTEsInJvbGUiOiJzdXBlcmFkbWluIiwic3ViIjoiODIyZGMzMTAtMzM2Mi00ZTNlLWFiZmQtZmMwYjA0MWUyMDBmIiwidXNlcm5hbWUiOiJzdXBlcmFkbWluIn0.jqfHBn9P8nG2rukDFN299P4xI5QFWzTXQzfnsTzqYJk

### 1. Create Tenant
# @name createTenant
POST {{baseUrl}}/v1/internal/tenant
Content-Type: application/json
X-Client-Key: {{clientKey}}

{
  "name": "Test Tenant 1",
  "subdomain": "testtenant1",
  "company_name": "Test Corp 1",
  "phone": "081234567890",
  "address": "Jakarta, Indonesia",
  "timezone": "Asia/Jakarta",
  "max_mikrotiks": 10,
  "max_network_users": 1000,
  "max_staff_users": 10
}



### 2. Get All Tenants
# @name listTenants
GET {{baseUrl}}/v1/internal/tenant/list
X-Client-Key: {{clientKey}}

> {%
    client.global.set("tenantId", response.body.data.id);
%}

### 3. Get Tenant by ID
GET {{baseUrl}}/v1/internal/tenant/{{listTenants.response.body.data.0.id}}
X-Client-Key: {{clientKey}}

### 4. Update Tenant
PUT {{baseUrl}}/v1/internal/tenant/{{listTenants.response.body.data.0.id}}
Content-Type: application/json
X-Client-Key: {{clientKey}}

{
  "name": "Test Tenant Updated",
  "company_name": "Test Corp Updated",
  "is_active": true,
  "status": "active"
}

### 5. Get Tenant Stats
GET {{baseUrl}}/v1/internal/tenant/{{listTenants.response.body.data.0.id}}/stats
X-Client-Key: {{clientKey}}

### 6. Delete Tenant
DELETE {{baseUrl}}/v1/internal/tenant/{{listTenants.response.body.data.0.id}}
X-Client-Key: {{clientKey}}
