services:
  redis:
    image: docker.io/library/redis:7-alpine
    container_name: app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_:/data:Z
    restart: unless-stopped

volumes:
  redis_: {}
